// <auto-generated />
using System;
using GraphQL.POC.API.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQL.POC.API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphQL.POC.API.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0d8732e-ff7c-407a-b6c1-e0339dbf62bd"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("eeb192d9-df1c-4399-82fd-74d4662034f1"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("fc56c65f-c207-4eca-ab71-523037db716f"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("bb4fd0ed-eef6-4cd9-8e2c-e442501eed17"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("78e0f8ab-b116-48ef-8e6d-78a567fe18c2"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("bb4fd0ed-eef6-4cd9-8e2c-e442501eed17"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("GraphQL.POC.API.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeb192d9-df1c-4399-82fd-74d4662034f1"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("bb4fd0ed-eef6-4cd9-8e2c-e442501eed17"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("GraphQL.POC.API.Entities.Account", b =>
                {
                    b.HasOne("GraphQL.POC.API.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
